[project]
name = "aethersync"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.aether-sync-access]
path = "contracts/aether-sync-access.clar"
depends_on = []

[contracts.aether-sync-core]
path = "contracts/aether-sync-core.clar"
depends_on = []

[contracts.aether-sync-integrity]
path = "contracts/aether-sync-integrity.clar"
depends_on = []

[contracts.aether-sync-metadata]
path = "contracts/aether-sync-metadata.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
